# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               "Alan's"
tagline:             'blog'
description:         "Alan's blog"
url:                 http://alansskim.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Alan
  url:               http://alansskim.github.io
  email:             alan@test.com

# Custom vars
version:             1.0.0

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["footnotes", "smart", "tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
